apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels: 
    app: ubuntu    
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
         "name" : "macvlan-conf",
         "interface" : "eth1",
         "ips" : ["172.20.10.134"]
      }]'
spec:
  containers:
  - name: ubuntu
    image: ubuntu:bionic
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
