apiVersion: v1
kind: Pod
metadata:
  name: basic-knf-superg
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
         "name" : "macvlan-conf",
         "interface" : "eth1",
         "ips" : ["10.0.0.127"]
      }]'
spec:
  containers:
  - name: samplepod
    image: cirros
